### PR TITLE
Update installer.sh

### PR DESCRIPTION
**Pull request by McFlyPartages**
Adding a sleep 20 after restarting network manager line 118 to give it time to restart.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @McFlyPartages, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#132).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
Why 20 seconds?

**Comment by McFlyPartages** [comment]
> Why 20 seconds?

the default time was not enough I took 20 seconds like that. I haven't tried less

**Comment by clemalex824** [comment]
It seems necessary, on RPi 4, to make a timeout of a few seconds otherwise the 'docker pull ...' command fails (https://forum.hacf.fr/t/installer-home-assistant-sur-raspberry-pi-ou-autres-sbc-debian-methode-docker-avec-supervisor/676/40?u=clemalex)

**Comment by ludeeus** [comment]
That is not related, that issue has been fixed allready

**Comment by McFlyPartages** [comment]
> That is not related, that issue has been fixed allready

It's been 2 days that I can not do the installation and thanks to this modification it works.

**Comment by frenck** [comment]
@McFlyPartages That issue listed above is not related and was fixed just a couple of hours ago.

**Comment by McFlyPartages** [comment]
> @McFlyPartages That issue listed above is not related and was fixed just a couple of hours ago.

Ok I will try again by passing your GitHub (because the raspberrypi4-64 version does not install the home assistant container).
After as said above I have been on it since yesterday and even again this evening it did not work 30 minutes before my PR.

**Comment by McFlyPartages** [comment]
I just restarted the installation and it worked, but since yesterday I just restarted installations, starting from clean images, with the same problem.

It seems resolved.

**Comment by ludeeus** [comment]
So there is no need for this anymore then?

**Comment by McFlyPartages** [comment]
> So there is no need for this anymore then?

You have to believe that no

**Pull request closed without merging**
