### PR TITLE
Added raspberrypi5-64 option...

### PR DESCRIPTION
**Pull request by sdotter**

### CODE REVIEW

**Comment by sdotter** [comment]
Nevermind; DISABLE_JEMALLOC needs to be set to true to work with RPI 5

**Comment by voron** [comment]
I ended up by building supervisor with extra `DISABLE_JEMALLOC` env var and using `raspberrypi4-64` as platform during dpkg configuration

**Comment by frenck** [comment]
> Nevermind; DISABLE_JEMALLOC needs to be set to true to work with RPI 5

This is fixed in our base images, but not available in the main images yet.

**Comment by HonzaJaros** [comment]
> I ended up by building supervisor with extra `DISABLE_JEMALLOC` env var and using `raspberrypi4-64` as platform during dpkg configuration

where is this `DISABLE_JEMALLOC` supposed to be?

**Comment by sdotter** [comment]
> > I ended up by building supervisor with extra `DISABLE_JEMALLOC` env var and using `raspberrypi4-64` as platform during dpkg configuration
> 
> where is this `DISABLE_JEMALLOC` supposed to be?

In docker compose yaml
But I did alternative fix

Add to /boot/firmware/config.txt:

kernel=kernel8.img

I run supervised home assistant with z2m + gpio dht22 sensor and some other stuff.
Runs awesome 👍

**Comment by HonzaJaros** [comment]
Too difficult, I don’t have the img anyway. But still can’t find the Jemalloc, can you be specific pls.

**Comment by voron** [comment]
> Too difficult, I don’t have the img anyway. But still can’t find the Jemalloc, can you be specific pls.

You'll need to build [supervisor](https://github.com/home-assistant/supervisor) container image yourself with the following patch
```diff
diff --git a/supervisor/docker/homeassistant.py b/supervisor/docker/homeassistant.py
index 0502420a..87279d26 100644
--- a/supervisor/docker/homeassistant.py
+++ b/supervisor/docker/homeassistant.py
@@ -174,6 +174,7 @@ class DockerHomeAssistant(DockerInterface):
                 ENV_TIME: self.sys_timezone,
                 ENV_TOKEN: self.sys_homeassistant.supervisor_token,
                 ENV_TOKEN_OLD: self.sys_homeassistant.supervisor_token,
+                "DISABLE_JEMALLOC": "true",
             },
             tmpfs={"/tmp": ""},
             oom_score_adj=-300,
```
And then use this image in your compose.yml instead of official one. It expects you to run HA supervisor via docker compose.yml, and supervisor will manage the rest. Here is my `compose.yml`
```yaml
version: '3'
services:
  supervisor:
    container_name: hassio_supervisor
      #image: "ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.12.0"
    image: "supervisor:0"
    volumes:
      - /run/supervisor:/run/os:rw
      - /run/udev:/run/udev:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /usr/share/hassio:/data:rw,slave
      - /run/docker.sock:/run/docker.sock:rw
      - /run/systemd-journal-gatewayd.sock:/run/systemd-journal-gatewayd.sock:rw
      - /run/dbus:/run/dbus:ro
    restart: no
    privileged: true
    environment:
      SUPERVISOR_SHARE: /usr/share/hassio
      SUPERVISOR_NAME: hassio_supervisor
      SUPERVISOR_MACHINE: raspberrypi4-64
    security_opt:
      - "apparmor:hassio-supervisor"
```

**Comment by IanW6374** [comment]
@voron Sorry fairly new to docker build so getting a few argument errors when trying to build the modified supervisor ... Can you elaborate on the docker build command you are using?

**Comment by voron** [comment]
> @voron Sorry fairly new to docker build so getting a few argument errors when trying to build the modified supervisor ... Can you elaborate on the docker build command you are using?

It's not required anymore, `raspberrypi4-64-homeassistant:2024.2.0` works fine with stock `aarch64-hassio-supervisor`

**Review by agners — APPROVED** [review]

**Comment by IanW6374** [comment]
@sdotter After selecting the rpi5-64 option I still need to add "lsm=apparmor" into  /boot/firmware/cmdline.txt

Is this intentional?

**Comment by sdotter** [comment]
> @sdotter After selecting the rpi5-64 option I still need to add "lsm=apparmor" into /boot/firmware/cmdline.txt
> 
> Is this intentional?

Yeah that isnt really something specific for just raspberry pi 5

**Pull request merged**
