### PR TITLE
fixes #162

### LINKED ISSUE #162: "homeassistant-supervised depends on os-agent", but os-agent:armhf is installed
Kia ora 👋

I have just tried installing a new "supervised" installation, and I am blocked since `homeassistant-supervised` does not recognise my installation of `os-agent:armhf`:

```
jon@OXYGEN:~/Containers/HomeAssistant$ lsb_release -d
Description:    Debian GNU/Linux 10 (buster)
jon@OXYGEN:~/Containers/HomeAssistant$ uname -a
Linux OXYGEN 5.10.63-rockchip64 #21.08.2 SMP PREEMPT Wed Sep 8 10:57:23 UTC 2021 aarch64 GNU/Linux
jon@OXYGEN:~/Containers/HomeAssistant$ sudo aptitude search os-agent
i   os-agent:armhf                                                                       - Home Assistant OS Agent
jon@OXYGEN:~/Containers/HomeAssistant$ sudo dpkg -i homeassistant-supervised.deb
(Reading database ... 40896 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
Leaving 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Leaving 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Leaving 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Leaving 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.0.1) over (1.0.1) ...
dpkg: dependency problems prevent configuration of homeassistant-supervised:
 homeassistant-supervised depends on os-agent.

dpkg: error processing package homeassistant-supervised (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 homeassistant-supervised
jon@OXYGEN:~/Containers/HomeAssistant$```

### PR DESCRIPTION
**Pull request by discip**
fixes https://github.com/home-assistant/supervised-installer/issues/162

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @discip

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant/supervised-installer#238).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by ikifar2012** [comment]
We support multiple architectures so this does not solve the issue

**Comment by ikifar2012** [comment]
the problem is that the os-agent package is named differently on armhf, I am going to try something but I will need you to test

**Comment by discip** [comment]
I assume I should close this PR than, right? 😊
Was not aware of the impact this would have on other architectures. 😅

**Comment by ikifar2012** [comment]
What I was going to do was specify a different package for each arch, but it appears as that doesn't need to be done as I have just checked all the deb files and all versions of the os-agent are the same package name and thus this should work 


@discip Can you try again with the latest version of the os-agent and can you confirm with `lsb_release -d` that you are in fact using vanilla Debian 11 Bullseye not a derivative

**Comment by discip** [comment]
It says `Debian GNU/Linux 11 (bullseye)`.
Will try the latest version.

**Comment by discip** [comment]
Unfortunately this is still not working!

**Comment by ikifar2012** [comment]
What device is this?

**Comment by discip** [comment]
It is a raspberry 4 with 8 GB of RAM.

**Comment by discip** [comment]
@ikifar2012
It is a **Raspberry Pi 4B 8GB**.

**Comment by discip** [comment]
@ikifar2012
Have you looked into this once more?
Any idea why this is not working?

**Comment by ikifar2012** [comment]
Well I haven't seen anyone else report this and unfortunately due to the chip shortage I do not have a Raspberry Pi 4

**Comment by discip** [comment]
@ikifar2012
As you can see here: https://github.com/home-assistant/supervised-installer/issues/162#issuecomment-1254901834 & here: https://github.com/home-assistant/supervised-installer/issues/162#issuecomment-1434957331, I am not the only one having this issue.

Do you have an official solution for that by now?

Thanks

**Pull request closed without merging**
