### PR TITLE
Update postinst - Add OS-agent and AppArmor into grub

### PR DESCRIPTION
**Pull request by hellresistor**
Add OS-Agent version detection automaticaly for last version. Add OS-Agent installation
Add "apparmor=1 security=apparmor" into '/boot/firmware/cmdline.txt' or '/etc/default/grub' files

### CODE REVIEW

**Comment by ikifar2012** [comment]
I'm not sure if we want the supervised package to install things for the user, not sure what the others think but the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) states "
The user first needs to install Debian and make sure all the required components are installed and are the correct version. They then need to run the installer script." Clearly stating the user is responsible for dependencies

**Comment by hellresistor** [comment]
without lines about apparmor will get unhealthy system :| (at least on my actually installation). It was a dedicate HA+Debian12aarch64

**Comment by ikifar2012** [comment]
After looking into this it appears that apparmor is on by default as per the Debian Wiki https://wiki.debian.org/AppArmor/HowToUse.
"If you are using Debian 10 "Buster" or newer, AppArmor is enabled by default so you can skip this step."

**Comment by hellresistor** [comment]
Interesting, this weekend will make new install and check with my eyes ^^'
thank you

**Pull request closed without merging**
