### PR TITLE
Issue #247 Ensure systemd-journal-gatewayd socket is correct

### LINKED ISSUE #247: Bug Report: installation steps don't mention enabling and mapping `systemd-journal-gatewayd`
### OS Version

Debian 11

### System Information

unsure

### What happened?

The ADR mentions this step in [additional supported conditions](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#additional-supported-conditions):
> Systemd journal gateway is enabled and mapped into supervisor as `/run/systemd-journal-gatewayd.sock`

The installation guide does not include any info on setting this up, it simply says to install `systemd-journal-remote`. It also doesn't currently seem to handle this as part of running the script, based on discussions in [here](https://community.home-assistant.io/t/2022-11-a-heck-of-a-release/483295/209?u=centralcommand).

Think there either needs to be guidance about how to do this in the step-by-step install guide or the script needs to handle this part.

### Machine Type

odroid-n2

### Installer output

_No response_

### Relevant log output

_No response_

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

### PR DESCRIPTION
**Pull request by p0wertiger**
We need to check whether /run/systemd-journal-gatewayd.sock is a socket file. If that's a directory, the socket unit won't start.
Also, socket configuration has been moved to unit override.

Fixes #247

### CODE REVIEW

**Comment by ikifar2012** [comment]
@p0wertiger did you see the comment above?

**Comment by p0wertiger** [comment]
Yes, hence the tag cla-signed

**Comment by ikifar2012** [comment]
> Yes, hence the tag cla-signed

I also asked in the review comment above if the line 2 `ListenStream=` is needed, since it is blank

**Comment by p0wertiger** [comment]
No, I don't see any review comments other than bot asking to sign CLA.

Empty `ListenStream` effectively causes to REPLACE the value, means delete the previous one and put in the new one from the next line. That's how systemd overrides work, if you omit the empty statement, it will be added to the original one, the unit would be listening both on network port and local socket.

**Pull request merged**
