### PR TITLE
Add option to run the installer unattended

### PR DESCRIPTION
**Pull request by iuriaranda**
Added an option so the installer script doesn't ask for input. Required for automated installations

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @iuriaranda, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#138).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
This installer comes with some warnings we want people to be aware of. We actually moved away from an unattended installer by choice.

Nevertheless, thanks for the suggestion. 👍

**Comment by iuriaranda** [comment]
Thanks for the quick and honest response.

In my opinion, people that would use the `--auto` flag are already aware of those warnings and consciously decide to procede anyway. That's why it's not a default option.

A side effect of not providing an official unattended installer is that people will eventually use workarounds and hacks, or will fork your repo (as I did) which could lead to drift from the official installer and to more unexpected consequences.

A possible solution to make sure people read the warnings is to also put them in the documentation, together with the `--auto` flag description, and make sure to inform people that they're using that flag at their own risk.

**Comment by zinefer** [comment]
I'm sitting here waiting for my ansible to come back after running a supervised install, something this code has done for me several times before. This must be why it is taking so long. ;)

I agree with @iuriaranda that I am going to have to make some hacks to get my install back to unattended.

**Pull request closed without merging**
