### PR TITLE
Use new machine flag

### PR DESCRIPTION
**Pull request by pvizeli**

### CODE REVIEW

**Comment by twocolors** [comment]
@pvizeli @frenck hi line
`if [ -z "${HOMEASSISTANT_DOCKER}" ]; then
    error "Found no Home Assistant Docker images for this host!"
fi`

env HOMEASSISTANT_DOCKER now not use in script ...

**Comment by egrekov** [comment]
Renamed HOMEASSISTANT_DOCKER to HASSIO_DOCKER, but forgotten in this block:
```bash
if [ -z "${HOMEASSISTANT_DOCKER}" ]; then
    error "Found no Home Assistant Docker images for this host!"
fi
```

**Comment by sauloonze** [comment]
Yes. That is causing issue.

**Comment by czm97176** [comment]
Would you please fix the issue ? i am geting the same error too. Thanks !

**Comment by mlohus93** [comment]
Ditto.  Worked perfectly last night but new install today is resulting in "[Error] Found no Home Assistant Docker images for this host!"

**Comment by Kanga-Who** [comment]
```
if [ -z "${HOMEASSISTANT_DOCKER}" ]; then
    error "Found no Home Assistant Docker images for this host!"
fi
```

Agreed, Removing this fixes the issue. Tested and working.

**Pull request merged**
