### PR TITLE
Change package homepage to github repository of deb source

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
I had a hard time tracking down the source of the installed
debian package.  Make life easier for the next one by providing a
link to the source in the package metadata.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @petterreinholdtsen, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#175).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by petterreinholdtsen** [comment]
[Home Assistant Bot]
> It seems you haven't yet signed a CLA. Please do so
> [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#175).
>
> Once you do that we will be able to review and accept this pull
> request.

I do not quite get it.  First of all, this change is not really
copyrightable, so licensing is not really relevant.  Second, why would I
want to sign away rights to help you?  If you do not want my help, just
state so.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by SirGoodenough** [comment]
> [Home Assistant Bot]
> It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#175). Once you do that we will be able to review and accept this pull request.
> I do not quite get it. First of all, this change is not really copyrightable, so licensing is not really relevant. Second, why would I want to sign away rights to help you? If you do not want my help, just state so.
> […](#)
> -- Happy hacking Petter Reinholdtsen

You are taking to the BOT there, BTW...  I don't think it will answer.
I bet the lawyers said to this so that there is proof the license is understood or something.

**Comment by frenck** [comment]
>  Second, why would I
> want to sign away rights to help you?  If you do not want my help, just
> state so.

We cannot accept pull requests if the CLA isn't signed. If you don't want to sign the CLA, that is fine, but we cannot merge it and you could probably better close the pull request.

Thanks 👍

**Comment by frenck** [comment]
Closing this stale, as the CLA still hasn't been signed.

**Pull request closed without merging**
