### PR TITLE
Switch to cgroupv1

### PR DESCRIPTION
**Pull request by ikifar2012**
Switch to cgroupv1 using the solution in https://github.com/home-assistant/supervisor/issues/3444#issuecomment-1055251172 mentioned by @sbyx

### CODE REVIEW

**Review by pvizeli — APPROVED** [review]

**Comment by fcastilloec** [comment]
Just wanted to comment for anybody else running into trouble, or coming from a google search.
The new version that implements this fix (v1.11.1), running on Raspberry Pi OS (I know it's not supported, only Debian Bullseye is supported), will encounter an error when trying to install.
Raspberry Pi OS doesn't use grub and will fail installation. If you need to enable cgroups v1, the values `cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory` must be added to `/boot/cmdline.txt`.
This is just for information purposes, not intending to add support for other OSs.

**Comment by jutonium** [comment]
@fcastilloec 's recommendation helped me!
But as stated before: Installing the HA supervisor on Raspberry Pi OS is not supported. Doing so has the following consequence:

```apt autoremove
[...]
1 not fully installed or removed. <--
```
And each invocation of `apt install / remove/ ...` leads to these few lines repeated over and over:
```grep: /etc/default/grub: No such file or directory
[info] Switching to cgroup v1
cp: cannot stat '/etc/default/grub': No such file or directory
dpkg: error processing package homeassistant-supervised (--configure):
 installed homeassistant-supervised package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 homeassistant-supervised
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
To solve this issue comment the lines concerning grub + cgroup in `/var/lib/dpkg/info/homeassistant-supervised.postinst`.
Then just run `apt autoremove` and the installation will successfully conclude and stop nagging.

**Comment by fcastilloec** [comment]
You can also create a dummy file at `/etc/default/grub` with the line `systemd.unified_cgroup_hierarchy=false` and the installation will go through without any issues and you can delete the file afterwards

**Comment by adeepn** [comment]
debian on arm does not support grub at most cases. you need to provide more powerful logic

**Comment by jutonium** [comment]
It seems only `systemd.unified_cgroup_hierarchy=false` has to be added to `/boot/cmdline.txt`. The options recommended by @fcastilloec did not work. Furthermore it is the same command which is written to the Grub configuration.

**Comment by ikifar2012** [comment]
Can anyone confirm to me exactly what needs to be added to `/boot/cmdline.txt`. I am working on a PR however right now I don't have a Pi to test on

**Comment by ikifar2012** [comment]
Here is the draft PR: https://github.com/home-assistant/supervised-installer/pull/206

**Pull request merged**
