### PR TITLE
Update installer.sh

### PR DESCRIPTION
**Pull request by superaft**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @superaft, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#147).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
Could you please elaborate on the change?

**Comment by superaft** [comment]
Installation failing when using WiFi. Need to wait after NetworkManager restart.

**Comment by frenck** [comment]
I rather see an implementation that checks if the connection is available before continuing. Adding a wait might be a working workaround, but is never stable or a correct solution.

**Comment by dheera** [comment]
This was also an issue for me. Too busy/lazy to sign a CLA right now but adding `sleep 10` before the `HASSIO_VERSON=...` line fixed it for me.

**Comment by frenck** [comment]
> but if CLA is the obstacle

The CLA isn't the obstacle. It shouldn't be implemented as just a delay. See my comment above.

**Comment by userosos** [comment]
Hi! Can add ti ending the script, please:
[info] Home Assistant supervised is now installed
[info] First setup will take some time **(!!may be more than 5 mins!!)**, when it's ready you can reach it here:
[info] http://192.168.89.10:8123
[info]

**Comment by pvizeli** [comment]
Fix with latest commit

**Pull request closed without merging**
