### PR TITLE
Remove the os-agent from depends list and add it as a suggestion

### PR DESCRIPTION
**Pull request by cociweb**
resolves issues:
https://github.com/home-assistant/supervised-installer/issues/185
https://github.com/home-assistant/os-agent/issues/57
https://github.com/home-assistant/os-agent/issues/63

### CODE REVIEW

**Comment by frenck** [comment]
The OS agent is required as per requirements.

**Comment by cociweb** [comment]
If it is really a requirement, I should propose to deliver it together with the installer

**Comment by frenck** [comment]
> If it is really a requirement, I should propose to deliver it together with the installer

We currently do not have an apt repository; feel free to contribute to the project to make such things happen.

**Comment by cociweb** [comment]
The apt repository won't solve the unhealthy supervised installation. :)

**Comment by frenck** [comment]
> The apt repository won't solve the unhealthy supervised installation.

Nor does ignoring our supported system requirements.

**Pull request closed without merging**
