### PR TITLE
Add info about running via ssh

### PR DESCRIPTION
**Pull request by Jeetah**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Jeetah, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#183).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by ikifar2012** [comment]
I am not sure where you are getting this info from, I have had no issues running this over SSH. Could you please elaborate?

**Comment by Jeetah** [comment]
Had this issue constantly with iterm2. Perhaps it depends on ssh app? Although, raspi-config is working totally fine via ssh.

**Comment by foreign-sub** [comment]
Hi @Jeetah,

no issues here just as @ikifar2012 says.
I believe what you want to say is "Some (misconfigured ?) terminal applications may have issues over ssh"

Cheers.

**Comment by Jeetah** [comment]
@foreign-sub I don't see any misconfiguration here...

**Comment by frenck** [comment]
The fact you run an UI on the machine, makes the machine already an invalid target for this installation type (and thus unsupported). The suggested addition here can never be correct the requirements are met.

Closing this PR because of the above reasoning.

**Pull request closed without merging**
