### PR TITLE
Dependency docker may differ in name

### PR DESCRIPTION
**Pull request by DarwinsBuddy**
e.g. raspberry pi os  armv7l
```
$ apt show docker
Package: docker
Version: 1.5-2
```

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @DarwinsBuddy, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;supervised-installer#209).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by ikifar2012** [comment]
We only support docker-ce

**Comment by DarwinsBuddy** [comment]
But not all distributions follow this naming convention. I guess you could also support podman or any other OCI compatible containerization software.

Is there a technical reason for not being able to install ha supervised on a machine having a docker package installed with probably the same capabilities as docker-ce?

**Comment by frenck** [comment]
> But not all distributions follow this naming convention.

We only support one distribution, so that is not a concern for the Home Assistant project.

Thanks for being willing contribute though 👍 

../Frenck

**Comment by DarwinsBuddy** [comment]
Seems like I completely overlooked that the package was renamed on many distribution upstreams to `docker-ce` consistently anyways https://docs.docker.com/engine/install/debian/

@frenck sry for the noise

**Pull request closed without merging**
